In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Orders_dirty.csv")

In [3]:
df.head()

,OrderID,CustomerID,Customer Name,Email,Phone_no,City,Category,Product,Quantity,UnitPrice,...,PaymentMethod,OrderDate,Status,Rating,Average_Rating,Total_Amount,Invalid Price,Invalid Quantity,Invalid Rating,Invalid Date
0,ORD013233,CUST04801,Vikas Sharma,vikas.sharma610@gmail.com,9738787236,Jaipur,Home Decor,Table Runner,2,1589.66,...,Cash on Delivery,06-12-2022,Cancelled,1,3.500324,3020.35,Valid,Valid,Valid,Valid
1,ORD018894,CUST00464,Aarav Iyer,aarav.iyer690@yahoo.com,9435901706,Delhi,Home Decor,Photo Frame,3,1105.70,...,UPI,12-10-2022,Pending,3,3.500324,3151.25,Valid,Valid,Valid,Valid
2,ORD002166,CUST03121,Kiran Kapoor,kiran.kapoor954@gmail.com,9777489925,Dehli,Furniture,TV Stand,6,5918.02,...,Net Banking,21-03-2023,Processing,4,3.500324,30181.90,Valid,Valid,Valid,Valid
3,ORD004089,CUST02855,Deepa Singh,deepa.singh398@gmail.com,9283637528,Kanpur,Sports,Football,1,1047.76,...,Debit Card,08-03-2023,Delivered,4,3.500324,1047.76,Valid,Valid,Valid,Valid
4,ORD012533,CUST01038,Diana Iyer,diana.iyer219@yahoo.com,9807232466,Mumbai,Home Decor,Cushion Cover,1,2102.00,...,Debit Card,31-03-2022,Delivered,2,3.500324,1576.50,Valid,Valid,Valid,Valid

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20065 entries, 0 to 20064
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           20065 non-null  object
 1   CustomerID        20065 non-null  object
 2   Customer Name     20065 non-null  object
 3   Email             20065 non-null  object
 4   Phone_no          20018 non-null  object
 5   City              20065 non-null  object
 6   Category          20065 non-null  object
 7   Product           20065 non-null  object
 8   Quantity          20065 non-null  int64
 9   UnitPrice         20065 non-null  float64
 10  Discount_Pct      19469 non-null  float64
 11  PaymentMethod     20065 non-null  object
 12  OrderDate         20065 non-null  object
 13  Status            20065 non-null  object
 14  Rating            20065 non-null  int64
 15  Average_Rating    20065 non-null  float64
 16  Total_Amount      20065 non-null  float64
 17  Invalid Price     20065 non-null  object
 18  Invalid Quantity  20065 non-null  object
 19  Invalid Rating    20065 non-null  object
 20  Invalid Date      20065 non-null  object
dtypes: float64(4), int64(2), object(15)
memory usage: 3.2+ MB

In [5]:
df.isnull().sum()

OrderID               0
CustomerID            0
Customer Name         0
Email                 0
Phone_no             47
City                  0
Category              0
Product               0
Quantity              0
UnitPrice             0
Discount_Pct        596
PaymentMethod         0
OrderDate             0
Status                0
Rating                0
Average_Rating        0
Total_Amount          0
Invalid Price         0
Invalid Quantity      0
Invalid Rating        0
Invalid Date          0
dtype: int64

In [6]:
df['Email'].fillna("Unknown", inplace=True)
df['City'].fillna("Unknown", inplace=True)
df['Rating'].fillna(0, inplace=True)

/tmp/ipykernel_5677/1531273467.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Email'].fillna("Unknown", inplace=True)
/tmp/ipykernel_5677/1531273467.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna("Unknown", inplace=True)
/tmp/ipykernel_5677/1531273467.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(0, inplace=True)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [10]:
df.groupby('Category')['Revenue'].sum()

Category
Automotive      8940634.62
Beauty          8147400.90
Books           5953711.01
Clothing        8578314.61
Electronics    14113532.95
Furniture      46902148.16
Groceries       2986567.23
Home Decor     15748967.56
Sports         12298029.03
Toys           10627539.87
Name: Revenue, dtype: float64

In [11]:
df.groupby('City')['Revenue'].sum().sort_values(ascending=False).head()

City
Surat        9918699.56
Kanpur       9797670.38
Hyderabad    9441292.42
Nagpur       9337553.65
Mumbai       9279149.68
Name: Revenue, dtype: float64